### ISSUE TITLE
Audio is off after Beat Saber 14th Feb 2022 release 

### ISSUE THREAD

**Issue by kanalive** [fabio914/RealityMixer#107]
The audio is not coming through anymore. I have been using Reality Mixer for at least a month, works perfectly in the past. After the 14th Feb 2022 Beat Saber release the audio stopped coming through to iPhone. 
My devices and apps:
oculus quest 2
iPhone 12 mini and iPad prof (Tried both, no audio coming through)
Latest Reality Mixer downloaded from Apple App Store

**Comment by fabio914** [comment]
This is an issue on their side. They said they were going to fix it: [Tweet](https://twitter.com/BeatSaber/status/1489612692067340292?s=20&t=cNdt02A7eu0OVbHqriVDKA)

**Comment by kanalive** [comment]
Great!! Thanks! Can’t wait to have this fixed
