### ISSUE TITLE
Reality Mixer doesn’t work anymore

### ISSUE THREAD

**Issue by BearUmbrella** [fabio914/RealityMixer#120]
Hi, I tried to do Mixed reality and I can’t get it to work. I checked to see if the wifi are the same, tried to see if the MRC option was in settings for Beat Saber (which it wasn’t), and tried to do the calibration again. I can’t get it to work! Please help, I just want to show my friends what I can do.

Edit: found out how to do it another way

**Comment by fabio914** [comment]
> tried to see if the MRC option was in settings for Beat Saber (which it wasn’t)

They had removed this option a long time ago, it was no longer necessary to enable it to make it work. However, I was testing the app again yesterday and it seems that many games stopped supporting Mixed Reality Capture, including Beat Saber.

**Comment by BearUmbrella** [comment]
What now, I have nothing else to use :/

**Comment by hisptoot** [comment]
BeatSaber version 1.28.0 works.
