### ISSUE TITLE
Is this tech compatible with VR apps via VirtualDesktop?

### ISSUE THREAD

**Issue by LinaEagle** [fabio914/RealityMixer#43]
In 1.7 we found it's not. It could be extremely powerful tool, do you have any purposes to integrate this feature? Do you any obstacles to achieve that? Should we have any additional plugins being implemented in custom application (ex. with Unity)? Maybe, I can find a way to contribute or help with it. Thank you in advance.

**Comment by fabio914** [comment]
I haven't tested with Virtual Desktop. I believe it's possible for Virtual Desktop to support Mixed Reality, but that would only mean that you'd be able to capture yourself looking at your virtual desktop within VR. 

Having my app capture PC VR games in Mixed Reality via Virtual Desktop, however, wouldn't be possible considering how the app works today.

**Comment by LinaEagle** [comment]
Ok, I see. Thank you.
