### ISSUE TITLE
Record Browser (WebXR) content

### ISSUE THREAD

**Issue by rmeertens** [fabio914/RealityMixer#46]
Hey all, thanks a lot for making this application! It all works fantastic! 
However, it seems that recording WebXR applications doesn't work right now. I tried it with both the default Oculus Browser as well as FireFox Reality (trying https://github.com/rmeertens/ImmersivePoints). 

Is this a problem which can be solved in RealityMixer? Or does it need to be changed by the programmers who made the browsers...

**Comment by fabio914** [comment]
Reality Mixer is based on the Oculus MRC plugin for OBS, and it currently only works with Unity and Unreal apps that use the Oculus SDK (Oculus Integration Package) and that implement Mixed Reality Capture. We're thinking on creating a Mixed Reality SDK for WebXR apps, and a version of Reality Mixer that'd be compatible with this SDK.

**Comment by rmeertens** [comment]
Thanks for the answer! Would it be easier to create a package for Three.js to start with? Would you then need to send over the scene to a new version of Reality Mixer?

**Comment by fabio914** [comment]
@rmeertens I forgot to update this, but I created a Mixed Reality solution for Three.js: https://github.com/fabio914/reality-mixer-js
