### ISSUE TITLE
Black screen shortly after starting capture

### ISSUE THREAD

**Issue by bsabiston** [fabio914/RealityMixer#63]
I tried to use this with an iPhone SE and AudioTrip on Quest 2. Initially it worked but as soon as I started a song, the screen went black - both on the phone and in the Quest.  When I moved it showed me superimposed on the black.  Tried several times with same result.
Any idea how to get it to work?

**Comment by fabio914** [comment]
Unfortunately, this is an issue with the Quest version of Audio Trip, you'll have to get in touch with them and ask them to properly support the Oculus Mixed Reality Capture.

**Comment by bsabiston** [comment]
Ah that's too bad.  I'll try contacting them. I figured it was a problem with their app since Beat Saber works great.. thanks!
