### ISSUE TITLE
assumption

### ISSUE THREAD

**Issue by ilker-aktuna** [fabio914/RealityMixer#71]
Since M1 is a newer chip I assume this would work on a device with M1 and Lidar 
is this assumption correct ?

**Comment by ilker-aktuna** [comment]
which one is better for this app :
1. ipad pro with M1 + Lidar
2. ipad 8 with A12 (no Lidar)

**Comment by ilker-aktuna** [comment]
in fact, I wonder if it would work with the second option  (A12 no Lidar) and would it work without green screen ?

**Comment by fabio914** [comment]
The LiDAR is recommended but not required. I'm able to get better results with my LiDAR-equipped iPad Pro 2020, but the app also works fine with my iPhone XS Max, that has a regular A12 chip and no LiDAR. It'd be interesting to test the app with the new M1 iPad Pro, but my understanding is that it has exactly the same LiDAR sensor as the iPad Pro 2020 and the iPhone 12.

**Comment by ilker-aktuna** [comment]
thanks. if Lidar is not required , only requirement is a A12 chip.
So basically it should work on a 8th gen 2018 iPad
