### ISSUE TITLE
Recording upside down

### ISSUE THREAD

**Issue by Silas33** [fabio914/RealityMixer#83]
Whenever I launch into any application the display shows me upright but the game I’m playing upside down. Is there any fix for this?

**Comment by fabio914** [comment]
What's the game that you're recording? There's an "Unflip ouput" option for this.

**Comment by Silas33** [comment]
It’s beat saber

**Comment by fabio914** [comment]
What's the version of the app that you're using? Try to recalibrate and make sure that "unflip output" is off before starting the mixed reality connection.

**Comment by Silas33** [comment]
Thanks you works great now!
