### ISSUE TITLE
Space Slurpies - not connecting 

### ISSUE THREAD

**Issue by Reenz11** [fabio914/RealityMixer#97]
Calibration goes well, app works with modded beat saber, but with space slurpies it keeps giving me the same error, and none of the parameters apply, I have done everything in this list. And I have not found any permissions regarding mrc in any of the sluprpie menus. Please advise 🥺
![6F8B31FB-1339-4D46-878D-57BE60A585DF](https://user-images.githubusercontent.com/89812602/131410533-632a092f-6023-459c-ba32-ed6565c94589.png)

**Comment by fabio914** [comment]
Did you complete the calibration before starting Space Slurpies? or did you try to connect to Space Slurpies after using Beat Saber? There's a chance that the connection with Beat Saber wasn't closed properly.

I'd recommend you to restart your Quest, then complete the calibration, quit the calibration app, start Space Slurpies, wait until it has finished initializing, and then try to start the mixed reality connection.

**Comment by Reenz11** [comment]
Yes, I have: 
completed the Cali
Close Cali app on quest 2
Open slurpies, open mixie mix up map
Then I try to connect with MRM app 
Then I get the error message
Both headset and phone are on same wifi band 
I no longer have the test flight app on my phone
I did with your first app
Is that the issue? But it works with beat saber! Also tried it with Arizona Sunshine, also worked

**Comment by Reenz11** [comment]
Should I try uninstalling space slurpies and re installing?

**Comment by Reenz11** [comment]
I did the uninstall and re install of the app, that did not help. I also reached out to the app dev, they said they were gonna reach out to you. I was advised by Oculus chat support to factory reset my headset because I have V32 update and no cloud. So I will keep you updated after I do this, I will reinstall everything and get back to you.

**Comment by fabio914** [comment]
I wonder if they've disabled Mixed Reality Capture on a newer version of Space Slurpies. I'll try to test this on my side with their newest version.

**Comment by Reenz11** [comment]
Reporting: I factory reset my device, and tried it again, and received the same message

**Comment by Reenz11** [comment]
I have also gotten in contact with the devs from Slurpies, they said they were going to contact you.

**Comment by fabio914** [comment]
I just tried it here as well. It behaves as if Space Slurpies didn't support Mixed Reality Capture. I wonder if they've disabled it in a recent update.

**Comment by Reenz11** [comment]
The devs got back to me: 
the way our new sdk works will not play nice for the time with the mixer app

it was an update with the game, and they are aware

**Comment by Reenz11** [comment]
Hello 👋, just wanted to report final answer for Slurpies and MR app, the devs said this 

Hey Reenz11, this will most likely be broke for a while as we have upgraded the game to the latest and greatest XR toolkit. We no longer use oculus sdk which is what the mixer app was using to pull the MR mode.

**Comment by fabio914** [comment]
Thanks for the update @Reenz11.

**Comment by Reenz11** [comment]
What have been doing is calibration, the close calibration, then open Slurpies, then open your map, then try to connect, and it fails. And also just open Slurpies, but connection fails again. But I will try again, I’ll get back to you

**Comment by Reenz11** [comment]
This is what the dev replied when I asked for an update:

Hey Reenz11, this will most likely be broke for a while as we have upgraded the game to the latest and greatest XR toolkit. We no longer use oculus sdk which is what the mixer app was using to pull the MR mode.
